language: node_js
node_js:     
- "stable"
cache:  
  directories:
    - "node_modules"
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "/src/"
  skip_cleanup: true
  on:
    tags: false